/* Generated By:JavaCC: Do not edit this line. DroidParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DroidParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int BUTTON = 6;
  /** RegularExpression Id. */
  int EDITTEXT = 7;
  /** RegularExpression Id. */
  int TEXTVIEW = 8;
  /** RegularExpression Id. */
  int LISTVIEW = 9;
  /** RegularExpression Id. */
  int RELLAYOUT = 10;
  /** RegularExpression Id. */
  int LINLAYOUT = 11;
  /** RegularExpression Id. */
  int CLICK = 12;
  /** RegularExpression Id. */
  int TEXT = 13;
  /** RegularExpression Id. */
  int VAR = 14;
  /** RegularExpression Id. */
  int EOL = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"Button\"",
    "\"EditText\"",
    "\"TextView\"",
    "\"ListView\"",
    "\"RelativeLayout\"",
    "\"LinearLayout\"",
    "\"Click\"",
    "<TEXT>",
    "<VAR>",
    "\"\\n\"",
  };

}
