/* Generated By:JavaCC: Do not edit this line. DroidParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DroidParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;
  /** RegularExpression Id. */
  int BUTTON = 7;
  /** RegularExpression Id. */
  int EDITTEXT = 8;
  /** RegularExpression Id. */
  int TEXTVIEW = 9;
  /** RegularExpression Id. */
  int EOL = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "<VARIABLE>",
    "\"Button\"",
    "\"EditText\"",
    "\"TextView\"",
    "\"\\n\"",
  };

}
